### ISSUE TITLE
addFetchEventListener: use Dispatcher instead of IORuntime?

### ISSUE THREAD

**Issue by kubukoz** [http4s/http4s-dom#263]
I was just checking out what `ServiceWorker` provides and noticed it hardcodes IO and requires `IORuntime`. Could this be replaced with `F[_]: Async` and creating a dispatcher? Or was it the entire point to keep `SyncIO` so that you can safely run the effect synchronously?

**Comment by armanbilge** [comment]
Good question, tl;dr this API is due for a complete refresh. We've had at least two relevant enhancements since I originally wrote it:

1. `Async[F]` now offers a `syncStep` method, so we no longer need to hardcode `IO` and `SyncIO`

2. The new JS runtime does not yield to the browser event loop so aggressively e.g. `unsafeRunAndForget()` starts as a microtask, so taking a `syncStep` is not so important anymore either
